spring:
  # DATABASE
  h2:
    console:
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/sbb
    driver-class-name: org.postgresql.Driver
    username: dbmasteruser
    password: ${DB_PASSWORD}

  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

# LOGGING
logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/mysite.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul

